### PR TITLE
Added phyplot function

### PR DESCRIPTION
**Pull request by mkborregaard**
A new branch based on the most recent version of Phylo

### CODE REVIEW

**Comment by mkborregaard** [comment]
OK, this should work.

**Comment by Ward9250** [comment]
I think I'm happy to merge this, but is there any word on the fan method?

**Comment by mkborregaard** [comment]
I haven't heard anything - would you like to wait until we are positive it works?

**Comment by Ward9250** [comment]
I'm tempted to merge it soon though, so as we can take what there is and settle on a way of dealing with annotations and all that jazz, which will make further development clearer and not guessing on how the phylogenetic will store annotations.

**Comment by mkborregaard** [comment]
I tend to agree - it is a very small edit that is needed once compose has been updated, and it currently works in IJulia, which I guess is where most people will be doing the plots anyway (because IJulia is born landscape).

**Comment by mkborregaard** [comment]
I just checked, and Compose has not yet been updated

**Comment by Ward9250** [comment]
I'm going to merge this now, we can wait for the gadfly change. Thanks @mkborregaard :+1:

**Comment by mkborregaard** [comment]
Very cool - I should think I could add the planned flexibility to it in January. Right now, I am having a problem rebasing my repo on the new version, because it seems you have two branches named Ward9250PhyloV1, and it looks like git is choosing the wrong one. Not really sure what to do about it...

**Comment by Ward9250** [comment]
Oh, that's really weird, I don't see a second branch on the page of my fork, and I don't have multiple in my Git on my local machine.... What if I just branched off the right Ward9250PhyloV1, and just call it something like 'Phylogenetics', it might get rid of that issue.

**Comment by mkborregaard** [comment]
It did help, thanks a lot. I am quite sure this is just me being awful at github...

**Pull request merged**
